### ISSUE TITLE
Dyskusja ogólna

### ISSUE THREAD

**Issue by gaargul** [gaargul/polskie-filtry-dodatkowe-zgloszenia#1]

**Comment by gaargul** [comment]
Jest to już mój drugi issue-tracker z dodatkowymi zgłoszeniami, ponieważ kilka dni temu konto z pierwszym issue trackerem `gargaamel` zostało zbanowane z nieznanych przyczyn przed adminów-pedofilów z administracji githuba, na mejle z prośbą o podanie przyczyny, nie odpisali, podobnie zbanowali mi konto `garrrgul`, również bez podania przyczyny, na mejlie również nie odpisali.

Tak samo zachowuje się admin-pedofil polskich filtrów banuje mi każde konto bez wytłumaczenia, nawet pomimo tego, że już przestałem masowo zgłaszać, bez powodu zbanował mi już następujące konta: `garrggul`, `gargulll` oraz `gaargul`.

Jak widać zarówno admin polskich filtrów jak i sama administracja githuba to pedofile zachowujące się jak wściekłe bydlęta, bany rozdawane bez powodu przez adminów-psychopatów powinny być karane i traktowane na równi z pedofilią.

Zapraszam pozostałych pedofilów-konfidentów do zgłaszana tego konta, za to, że jest tu napisana prawda o psycholach-adminach, aż jestem ciekaw czy admini-pedofile z administracji znowu zbanują za nic kolejne konto.

**Comment by krystian3w** [comment]
Jak coś reklam wewnętrznych nie mam ochoty pchać na dwa repozytoria.

**Comment by gaargul** [comment]
Wiem, to są zgł. dla @KonoromiHimaries, dlatego właśnie w pierwszym zgłoszeniu reklamy wewn.  (https://github.com/gaargul/polskie-filtry-dodatkowe-zgloszenia/issues/10#issue-411185370) specjalnie go zawołałem:

> gaargul: Reklama wewn. po prawej @KonoromiHimaries:

**Comment by gaargul** [comment]
krystian3w może ty zawołałbyś KonoromiHimaries, bo na moje zawołanie chyba nie przyjdzie, albo nie czyta powiadomień.

**Comment by krystian3w** [comment]
Jak coś troszkę wolniej będę dodawać, bo dzisiaj robiłem z 10 rzeczy na raz i css umieszczony w uBO zamiast w Stylus, pozwolił mi wykasować z 2644 filtrów social.

**Comment by gaargul** [comment]
Żeby tylko znowu bana mi nie dali, bo wszystkie zgłoszenia wyparują.

**Comment by krystian3w** [comment]
To wrzuć na web archive org?

---

Zarchiwizowałem 4 zakładki - raczej linki mi starczą jak się większość rzuca w oczy i nie powraca gdzieś z winy AdGuarda lub innych bugów z przemieleniem 80k filtrów kosmetycznych przykładowo.

**Comment by gaargul** [comment]
Pedofil dalej banuje po złości, zbanował mi znowu bez powodu kolejny nick `gaarguul`, tylko za to, że pomagam, przecież nie robię od jakiegoś czasu tam masowych zgłoszeń, więc o co temu psychopacie chodzi, chyba jest jakiś niewyżyty i zwyczajnie robi po złości.

**Comment by krystian3w** [comment]
Chyba mój Nano Adblocker został "skompromitowany", będę musiał go przeinstalować, by mi nie przekłamywał co jest wycięte, a co nie.

**Comment by krystian3w** [comment]
Widziałeś to, teraz nie mam błędów 5XX w blame a ładuje się pusty:

https://github.com/easylist/easylist/blame/fe5f88be91b92de72efe94cfa4b94bc874f62f71/easylist/easylist_general_hide.txt - ciekawiło mnie kto zrobił dwa generyki a nie chce mi się grzebać w shellu i komendami to wygrzebać najgłębiej jak się da.

**Comment by gaargul** [comment]
No u mnie też pusty.
