### ISSUE TITLE
jak-zdobyc-dziewczyne.pl

### ISSUE THREAD

**Issue by gaargul** [gaargul/polskie-filtry-dodatkowe-zgloszenia#115]
Social ikona/przycisk na dole:
http://jak-zdobyc-dziewczyne.pl/grupa/

![ss568](https://user-images.githubusercontent.com/47386482/53289087-84d75180-3791-11e9-8755-103a7c1b9f56.png)

**Comment by krystian3w** [comment]
Ok sprawdzę może wyciąłem www z linka?

**Comment by gaargul** [comment]
Już jest ok, zniknęło.

**Comment by krystian3w** [comment]
`jak-zdobyc-dziewczyne.pl#?#.right > ul:-abp-has(img[src="img/but_content3_youtube1.png"])`

czyli niby OK, u mnie nagle widać aż 3 przyciski i nie wymuszałem aktualizacji, a na zablokowanie się listy niby pomóc powinno odczekanie dwóch godzin i atrybut "`_`"  dostanie nowy numerek z daty / godziny.

**Comment by krystian3w** [comment]
Jak coś zmieniłem na szukanie tekstu `społecznościowych`, bo do obrazka dali base64... - niby nisko to może ukrywać po pełnym załadowaniu witryny.

**Comment by gaargul** [comment]
> krystian3w: czyli niby OK, u mnie nagle widać aż 3 przyciski i nie wymuszałem aktualizacji

Do czasu, bo teraz też nic nie dotykałem, a tylko wszedłem przed chwilą dosłownie i też są nagle 3 przyciski.

**Comment by krystian3w** [comment]
A już wiem, chyba NIE wchodzimy w podstronę, stąd wraca.

**Comment by gaargul** [comment]
Przed chwilą zaktualizowałem filtry social bo miałem wersję z 2:00 w nocy a teraz jest wersja z 18:00 i już nie ma żadnego przycisku, tylko nie wiem czy pomogła aktualizacja, czy po prostu znowu losowo się schowały przypadkiem, a za chwilę znowu mogą wyskoczyć.

**Comment by krystian3w** [comment]
```
||www.jak-zdobyc-dziewczyne.pl/wp-content/uploads/*/56x56xyoutube-icon.png*
||www.jak-zdobyc-dziewczyne.pl/wp-content/uploads/*/56x56xFacebook_icon.png*
```

niby na blogu też jest, inna sprawa, że zdechł w 2011...

**Comment by krystian3w** [comment]
wersje z `www` też dociąłem sieciowo i 1 ramkę kosmetycznie.

**Comment by gaargul** [comment]
> krystian3w: A już wiem, chyba NIE wchodzimy w podstronę, stąd wraca.

Nie wiem jak ty, ale ja jestem niemalże pewien, że wchodziłem w podstronę w podany link, ale ręki sobie uciąć nie dam, zresztą w drugim zgłoszeniu https://github.com/gaargul/polskie-filtry-dodatkowe-zgloszenia/issues/121 nie było podstrony, więc pomylić się nie mogłem, a zdarzył się taki sam przypadek, możliwe, że coś u mnie w uBO albo przeglądarce się przywiesiło na kilka minut, różne cuda już się zdarzały więc nic mnie już nie zdziwi, tak czy inaczej najważniejsze, że już jest powycinane, jutro jeszcze zajrzę kontrolnie na obydwie strony.
