### ISSUE TITLE
kobieceporady.pl

### ISSUE THREAD

**Issue by gaargul** [gaargul/polskie-filtry-dodatkowe-zgloszenia#119]
Social link na dole po ~~lewej~~ prawej:

![ss572](https://user-images.githubusercontent.com/47386482/53289229-c2d57500-3793-11e9-8d1e-8ad58e613b7b.png)

**Comment by krystian3w** [comment]
Niedomknięty atrybut `href`.

**Comment by gaargul** [comment]
Dalej to mam na wersji filtrów z godz. 18:00 (przed chwilą wszedłem).

**Comment by krystian3w** [comment]
PS. dla ułatwienie etykietkę daje od razu jak dodam jakiś filtr na stronę, szkoda mi czekać 4 godziny aż Circle scali i posortuje, a też nie lubię za bardzo z okienek to edytować.

**Comment by gaargul** [comment]
Rozumiem, ale ~~zdaje się, że~~ o godz. 18:00 była aktualizacja listy i została dodana twoja poprawka sprzed 3 godzin https://github.com/gaargul/polskie-filtry-dodatkowe-zgloszenia/issues/119#issuecomment-469278971?

**Comment by krystian3w** [comment]
> ` twoja poprawka sprzed 3 godzin`

A to pewnie teraz niby nie pasuje `$` = teraz widzę, że brakuje `/`, jak mam `$`, jakby był daszek, to by przeszło.

 zmienię na sztywniejsze, nie ważne co będzie w ul:

`##div.columns:nth-of-type(3) > ul.no-bullet:nth-of-type(1) > li:nth-of-type(3)` https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/0db3a92960e2942d6453929017f15768ab9f8559

**Comment by gaargul** [comment]
Ok już jest wycięte.
