### ISSUE TITLE
mojacukrzyca.org

### ISSUE THREAD

**Issue by gaargul** [gaargul/polskie-filtry-dodatkowe-zgloszenia#121]
Social ikona przycisk u góry:

![ss574](https://user-images.githubusercontent.com/47386482/53289264-47c08e80-3794-11e9-8e52-af4229749709.png)

**Comment by krystian3w** [comment]
```
||mojacukrzyca.org/grafika/logo/20170801/rss.gif
||mojacukrzyca.org/grafika/logo/20170801/snapchat.gif
||mojacukrzyca.org/grafika/logo/20170801/youtube.gif
||mojacukrzyca.org/grafika/logo/20170801/nk.gif
```

**Comment by gaargul** [comment]
Dalej to mam na wersji filtrów social z godz. 18:00 (przed chwilą wszedłem) i nawet mam po dodaniu tych filtrów wyżej

_Dodane po kilku minutach:_
Dziwne, teraz wszedłem znowu, i już nie ma z tymi filtrami podanymi wyżej, kolejny przypadek, że coś raz jest wycinane, a innym razem nie.

**Comment by gaargul** [comment]
Dziwne, teraz wszedłem znowu, i już nie ma z tymi filtrami podanymi wyżej.

**Comment by krystian3w** [comment]
A ja nie przypominam sobie docinania nk, zwłaszcza że mają tabele bez ID/Class, tak to jest jak się zrobiło 40 na raz i potem już przeszła motywacja.

**Comment by krystian3w** [comment]
Mam nadzieje, że grafik po 2 latach nie zmienią a jak już to przy pełnej przebudowie.

**Comment by krystian3w** [comment]
I jestem ciekaw czy RSS się za tydzień odpali.
