### ISSUE TITLE
centrumdialogu.com

### ISSUE THREAD

**Issue by gaargul** [gaargul/polskie-filtry-dodatkowe-zgloszenia#129]
Social ikony/przyciski u góry po prawej:

![ss581](https://user-images.githubusercontent.com/47386482/53298927-94f43d00-3834-11e9-8903-d8863a024433.png)

**Comment by krystian3w** [comment]
Ja mam tylko bip.

**Comment by gaargul** [comment]
Ja też, bo to kolejny naprawiony duplikat...https://github.com/gaargul/polskie-filtry-dodatkowe-zgloszenia/issues/99#issuecomment-469008787
