### ISSUE TITLE
inzynieria.com

### ISSUE THREAD

**Issue by gaargul** [gaargul/polskie-filtry-dodatkowe-zgloszenia#137]
Social ikony/przyciski u góry po prawej:

![ss541](https://user-images.githubusercontent.com/47386482/53328935-5077a880-38eb-11e9-8b4e-2756c0ee3384.png)

**Comment by krystian3w** [comment]
tych nie widzę, mam inne:

`inzynieria.com##.cd-nav-social.list-inline > li`

**Comment by gaargul** [comment]
Ja mam to dalej na Firefoxie i Operze, a z kolei nie widzę tego co ty masz.

**Comment by krystian3w** [comment]
wskoczyło po zoomowaniu, RWD error?

**Comment by krystian3w** [comment]
`##.nav-social-top > li:nth-of-type(-n+5)`

**Comment by gaargul** [comment]
Teraz jest ok.
