### ISSUE TITLE
di.com.pl

### ISSUE THREAD

**Issue by gaargul** [gaargul/polskie-filtry-dodatkowe-zgloszenia#144]
Social ikona/przycisk u góry:

![ss548](https://user-images.githubusercontent.com/47386482/53336759-98082f80-38ff-11e9-95d9-4386130142a0.png)

**Comment by krystian3w** [comment]
Nie mam / wycięte.

**Comment by gaargul** [comment]
Dalej to mam, na Firefoxie i Operze, i nie przywraca mi tego Adguard.

**Comment by krystian3w** [comment]
Może błąd w ~~EI~~?

**Comment by krystian3w** [comment]
błąd w polski RSS:

`.subbelka > ul > li:nth-of-type(6)` - może czas przerobić na wykrywanie url...

**Comment by krystian3w** [comment]
No to trochę wykrywając url i trochę blokując grafiki
