### ISSUE TITLE
kucharenka.pl

### ISSUE THREAD

**Issue by gaargul** [gaargul/polskie-filtry-dodatkowe-zgloszenia#162]
Social mini-galeira na dole + ikona/przycisk po lewej:

![ss_003](https://user-images.githubusercontent.com/47386482/53340793-22559100-390a-11e9-9a92-1ec1bb6c4767.png)

**Comment by krystian3w** [comment]
przycisk mi nie wycieka

**Comment by gaargul** [comment]
U mnie też już tego przycisku nie ma.
