### ISSUE TITLE
scanner.com.pl

### ISSUE THREAD

**Issue by gaargul** [gaargul/polskie-filtry-dodatkowe-zgloszenia#179]
Social widżet wysuwany scrollujący po lewej:

![anim 003](https://user-images.githubusercontent.com/47386482/53418637-88104e80-39d8-11e9-9b0e-d827c692a1ee.gif)

**Comment by krystian3w** [comment]
Nie mam / nie ładuje się.

**Comment by krystian3w** [comment]
Jak coś do starego generyka doczepiłem `##.pwebbox.pweb-theme-fbnavy`

**Comment by gaargul** [comment]
U mnie też już tego nie ma.

**Comment by krystian3w** [comment]
Ciekawe na ile przywracało to coś z list z jakiś ostatnio zrezygnowałeś. Może jak jest rozwijana to zobaczyć co autor na to - może zrobi lżejsze / dokładniejsze dopuszczenia u siebie.
