### ISSUE TITLE
e-madame.pl

### ISSUE THREAD

**Issue by gaargul** [gaargul/polskie-filtry-dodatkowe-zgloszenia#2]
https://github.com/MajkiIT/polish-ads-filter/issues/12158#issuecomment-464428379

> 
> @krystian3w:
> 
> W sumie to tam jest od `n` `a` `j` `e` `b` `a` `n` `i` `a` facebooka
> 
> niby przegapiasz aż 5 elementów: `www.e-madame.pl##.widget-item.widget_facebook`

Rozumiem, że te elementy mają klasę `.widget_facebook` i filtr te elementy chwyta, ale w praktyce patrzyłem tylko po tytułach/nagłówkach i gdzie kierują (nie zagłębiałem się w kod):
- te elementy nie mają nazw/nagłówków związanych z socjalem:  "Ostatnio dodane", "Gorące tematy", "Na czasie", "Najnowsze / Popularne"
- po kliknięciu kierują do artykułu na stronie wewnętrznej serwisu

Krótko to ujmując, poza klasą zawierającą "widget_facebook" w nazwie te elementy nie wydają się, żeby były socjalne...to jak to jest? O co tu kaman?

**Comment by krystian3w** [comment]
OK, w takim razie trzeba użyć `#facebook-1`
