### ISSUE TITLE
saga.info.pl

### ISSUE THREAD

**Issue by gaargul** [gaargul/polskie-filtry-dodatkowe-zgloszenia#3]
https://github.com/MajkiIT/polish-ads-filter/issues/12170#issuecomment-464431276

> @krystian3w: a po prawej wigdet wyciął AdGuard team?

Fanboy’s Social Blocking List , ale AdGuard Social też to wycina, którakolwiek z nich to wycina, dopiero po wyłączeniu obydwu list pojawia się ten widżet. (dla pewności sprawdziłem zarówno na Firefox jak i Operze).

**Comment by krystian3w** [comment]
Dobrze, to ciekawe czemu mi wyciekło :rofl:

**Comment by gaargul** [comment]
Potwierdzam - social zrobione, zostaje sprawa dla reportera/krystian3w, czy jakoś mogę pomóc ze swojej strony żebyśmy rozwikłali tę zagadkę?

**Comment by krystian3w** [comment]
Nie mam pojęcia, bo potem już nie wyciekało, a wersja dev na pewno mi się nie pobrała.
