### ISSUE TITLE
reklamy-arek.blogspot.com

### ISSUE THREAD

**Issue by gaargul** [gaargul/polskie-filtry-dodatkowe-zgloszenia#31]
1 Reklama wewn. u góry po prawej:
![ss567](https://user-images.githubusercontent.com/47386482/52913950-2e66a080-32c3-11e9-9b77-923ba7299f08.png)

2 Tło reklamowe - to nie wiem czy to nie do filtrów EI ==> Polskie Filtry Elementów Irytujących - Tła Zawierające Autoreklamy ?
![ss_016](https://user-images.githubusercontent.com/47386482/52913974-65d54d00-32c3-11e9-88cc-ac0a3b879d5d.png)

**Comment by krystian3w** [comment]
Jak dla mnie można wyciąć w EI za 6 minut, nie wiem do jakiego modułu to trafia, aż tak ich nie znam - dowiemy się po 15.

**Comment by gaargul** [comment]
Potwierdzam - tło wycięte, zostaje rekl. wewn. dla KonoromiHimaries.
