### ISSUE TITLE
amberexpo.pl

### ISSUE THREAD

**Issue by gaargul** [gaargul/polskie-filtry-dodatkowe-zgloszenia#43]
Social widżety wysuwane i scrollujące po prawej:

![anim 002](https://user-images.githubusercontent.com/47386482/52977859-36136b80-33cf-11e9-9e60-77c8c8363c5b.gif)

**Comment by krystian3w** [comment]
Facebooka nie mam przywraca go AdGuard, przypadkiem?

**Comment by gaargul** [comment]
Nie przywraca, hmm na Operze też nie mam Facebooka, ale na Firefoxie mam.

**Comment by gaargul** [comment]
Hmm na Operze nie też nie mam FAcebooka, ale na Firefoxie mam.

**Comment by krystian3w** [comment]
A więc ciekawe, mnie mignie i już go nie ma. Firefox.

**Comment by krystian3w** [comment]
Nie umiem wyjaśnić jak to mi znika, nie EI, niby Fanboy.

No to dodam takie coś:

```
##body > div[style]:nth-of-type(n+3):nth-of-type(-n+4) > .handle_fb
```

**Comment by gaargul** [comment]
Działa / wycina ten filtr.
