### ISSUE TITLE
huee.in

### ISSUE THREAD

**Issue by gaargul** [gaargul/polskie-filtry-dodatkowe-zgloszenia#5]
Social ikony/przyciski na dole po lewej:

![ss539](https://user-images.githubusercontent.com/47386482/52912895-38cf6d00-32b8-11e9-9144-4aee133ea0aa.png)

**Comment by krystian3w** [comment]
```html
<alert-message>
    <alert-message-content>
       Trwa aktualizacja - pozostały jeszcze trzy sekcje i linki. Prosimy o cierpliwość!
    </alert-message-content>
</alert-message>
```

**Comment by krystian3w** [comment]
Część w właściwym pliku do subskrypcji będzie pewnie koło 18.
