### ISSUE TITLE
zawisza.szkola.pl

### ISSUE THREAD

**Issue by gaargul** [gaargul/polskie-filtry-dodatkowe-zgloszenia#57]
Sociale:

1 ikony/przyciski u góry po prawej:
![ss555](https://user-images.githubusercontent.com/47386482/52979069-45e17e80-33d4-11e9-836f-1836af49c834.png)

2 ikony/przyciski na dole po prawej:
![ss554](https://user-images.githubusercontent.com/47386482/52979082-53970400-33d4-11e9-8e01-ed13dc845c4d.png)

3 baner na dole z klikalnym przyciskiem:
![ss553](https://user-images.githubusercontent.com/47386482/52979066-41b56100-33d4-11e9-8da5-813ecfb8ef14.png)

**Comment by gaargul** [comment]
To "3 baner na dole z klikalnym przyciskiem:" dalej jest.

**Comment by krystian3w** [comment]
`zawisza.szkola.pl#?#.enigma_callout_area:-abp-contains(Facebook'u)`

**Comment by krystian3w** [comment]
A skakać i i tak za mocno już skacze przez dziwne slidery.

**Comment by gaargul** [comment]
Działa.
