### ISSUE TITLE
wymiennik.com

### ISSUE THREAD

**Issue by gaargul** [gaargul/polskie-filtry-dodatkowe-zgloszenia#63]
Social link na dole po prawej:

![ss562](https://user-images.githubusercontent.com/47386482/53003017-56bede00-342e-11e9-98b6-3395fbef1557.png)

**Comment by krystian3w** [comment]
W  uBO / AdGuard najwyżej zablokuje klikanie, na chama wcisnęli?

**Comment by gaargul** [comment]
Ok, to można chociaż spróbować zablokować klikanie.
