### ISSUE TITLE
twitturly.com

### ISSUE THREAD

**Issue by gaargul** [gaargul/polskie-filtry-dodatkowe-zgloszenia#65]
Social banery/przyciski u góry po lewej:

![ss564](https://user-images.githubusercontent.com/47386482/53008637-22511f00-343a-11e9-859c-326512513559.png)

**Comment by krystian3w** [comment]
Jak dla mnie mają takie głupie logo...

**Comment by gaargul** [comment]
Tu cały baner lub jak kto woli dwa obok tworzące jeden...:

![ss539](https://user-images.githubusercontent.com/47386482/53043571-0a54bc00-3489-11e9-85bb-d2f53aeddcb0.png)

No, ale tak czy inaczej to baner social, duży, jeebutny, drażniący, ja bym wyciął, bo co ten baner niby reprezentuje - nic poza tym żeby ich polubić na FB, niech sobie wstawią normalne logo, oczywiście decyzja należy do was.

**Comment by gaargul** [comment]
Rozumiem, że decyzja jest taka, że to zostaje i mam zamykać?

**Comment by krystian3w** [comment]
Tak.
