### ISSUE TITLE
natemat.de

### ISSUE THREAD

**Issue by gaargul** [gaargul/polskie-filtry-dodatkowe-zgloszenia#66]
Social ikony/przyciski na dole:

![ss565](https://user-images.githubusercontent.com/47386482/53008773-67755100-343a-11e9-9425-311d102b6197.png)

**Comment by krystian3w** [comment]
oni ich losują w tym div-ie :rofl:

---

`##.author-icons > li > a:not([href*="//natemat.de"])`
