### ISSUE TITLE
kobiecareaktywacja.pl

### ISSUE THREAD

**Issue by gaargul** [gaargul/polskie-filtry-dodatkowe-zgloszenia#77]
Social ikony/przyciski u góry po prawej - mam je tylko na Firefoxie, na Operze nie mam:

![ss585](https://user-images.githubusercontent.com/47386482/53020238-c648c380-3456-11e9-9fe2-59d9874d9248.png)

**Comment by krystian3w** [comment]
Ja mam 1 z dwóch na Firefox, sprawdź czy masz zaznaczone ukrywanie  błędu ładowania grafik:

`Ukrywaj symbole zastępcze zablokowanych elementów`

Wtedy uBO z automatu generuje filtr kosmetyczny na podstawie sieciowego.

**Comment by krystian3w** [comment]
A pop-up fancybox z FB like wycina ci poprawnie, bo bym zwalił na pierwszy rozruch chrome że mi wyjątkowo wskoczył.

Taki blokujący przewijanie.

**Comment by gaargul** [comment]
> krystian3w:
> 
> Ja mam 1 z dwóch na Firefox,

Ja nie mam żadnej, bo tą jedną, którą ty masz mi wycina dodatkowa lista (https://mrsatterly.com/abp_filters.html), której pewnie i tak mało kto używa , więc i tak do wycięcia się kwalifikowało, skoro już i tak zrobiłem omyłkowo zgłoszenie.

> krystian3w:
> 
> sprawdź czy masz zaznaczone ukrywanie błędu ładowania grafik:
> 
> `Ukrywaj symbole zastępcze zablokowanych elementów`
> 
> Wtedy uBO z automatu generuje filtr kosmetyczny na podstawie sieciowego.

Trafiłeś, faktycznie miałem odznaczone.


> krystian3w:
> 
> A pop-up fancybox z FB like wycina ci poprawnie, bo bym zwalił na pierwszy rozruch chrome że mi wyjątkowo wskoczył.
> 
> Taki blokujący przewijanie.

Popup mi żaden nie wyskakuje ani na Firefoxie ani na Operze.
