### ISSUE TITLE
citrix.com.pl

### ISSUE THREAD

**Issue by gaargul** [gaargul/polskie-filtry-dodatkowe-zgloszenia#9]
Social ikony/przyciski na dole:

![ss542](https://user-images.githubusercontent.com/47386482/52913050-176f8080-32ba-11e9-9ac9-f31f27f91202.png)

**Comment by gaargul** [comment]
Dalej to jest zarówno na Firefoxie jak i na Operze.

**Comment by krystian3w** [comment]
Efekt robienia na szybko, najpewniej nawet nie otwierałem strony.

**Comment by krystian3w** [comment]
`citrix.com.pl##.ctx-follow-wrap > div, .ctx-follow-wrap > ul[class]`
