### ISSUE TITLE
festiwalbiegowy.pl

### ISSUE THREAD

**Issue by gaargul** [gaargul/polskie-filtry-dodatkowe-zgloszenia#92]
Social ikona/przycisk na dole:

![ss544](https://user-images.githubusercontent.com/47386482/53284807-78370700-3759-11e9-8a26-f37ce04fc5d1.png)

**Comment by gaargul** [comment]
Dalej to mam, na Firefoxie i Operze, i nie przywraca mi tego Adguard.

**Comment by krystian3w** [comment]
To zobaczymy co na to Chrome? Albo może w liscie EI błąd.

**Comment by krystian3w** [comment]
Mam wycina to "`##.rss`" więc do  przejrzenia ~~fanboy~~ / polski RSS.
