### ISSUE TITLE
ipa-katowice.org

### ISSUE THREAD

**Issue by gaargul** [gaargul/polskie-filtry-dodatkowe-zgloszenia#96]
Social ikony/przyciski scrollujące po prawej:

![ss549](https://user-images.githubusercontent.com/47386482/53285536-cbad5300-3761-11e9-90e6-738e1a6f89a5.png)

**Comment by krystian3w** [comment]
nie mam tego, i dodatkowo cookies wycięte chyba sieciowo, bo rozwalony komunikat jakby brakowało CSS.

**Comment by gaargul** [comment]
Faktycznie, przywracała mi to jedna z dodatkowych list: 
https://raw.githubusercontent.com/anarki999/Adblock-List-Archive/master/Better.fyiTrackersBlocklist.txt

**Comment by krystian3w** [comment]
Jak coś będzie źle docięte to wiesz, reopen, usuwanie etykiet

**Comment by gaargul** [comment]
Wywaliłem już tę listę: https://github.com/gaargul/polskie-filtry-dodatkowe-zgloszenia/issues/96#issuecomment-469005243
