### ISSUE TITLE
swiatzlotasklep.pl

### ISSUE THREAD

**Issue by gaargul** [gaargul/polskie-filtry-dodatkowe-zgloszenia#99]
Sociale:

1 widżet wysuwany/scrollujący po prawej:
![anim 003](https://user-images.githubusercontent.com/47386482/53285602-ba187b00-3762-11e9-83f1-aae7f8f2014f.gif)

2 baner klikalny po prawej:
![ss553](https://user-images.githubusercontent.com/47386482/53285607-c1d81f80-3762-11e9-83bb-55239e6e5420.png)

**Comment by krystian3w** [comment]
`#fb-slide-gfx, #box_cusConBody_80` - niby więc u mnie zablokowane.

**Comment by gaargul** [comment]
U mnie też, ale to nie dziwne, skoro zapomniałeś, że naprawiłeś duplikat mojego zgłoszenia:  
https://github.com/MajkiIT/polish-ads-filter/issues/12267, podobnie jak inne duplikaty: 
https://github.com/MajkiIT/polish-ads-filter/issues/12266 odnośnie https://github.com/gaargul/polskie-filtry-dodatkowe-zgloszenia/issues/97 i
https://github.com/MajkiIT/polish-ads-filter/issues/12273 odnośnie https://github.com/gaargul/polskie-filtry-dodatkowe-zgloszenia/issues/120 i
https://github.com/MajkiIT/polish-ads-filter/issues/12275 odnośnie https://github.com/gaargul/polskie-filtry-dodatkowe-zgloszenia/issues/129 i
https://github.com/MajkiIT/polish-ads-filter/issues/12276 odnośnie https://github.com/gaargul/polskie-filtry-dodatkowe-zgloszenia/issues/135 i
https://github.com/MajkiIT/polish-ads-filter/issues/12293 odnośnie https://github.com/gaargul/polskie-filtry-dodatkowe-zgloszenia/issues/141 i
https://github.com/MajkiIT/polish-ads-filter/issues/12317 odnośnie https://github.com/gaargul/polskie-filtry-dodatkowe-zgloszenia/issues/214 i
https://github.com/MajkiIT/polish-ads-filter/issues/12519 osnośnie https://github.com/gaargul/polskie-filtry-dodatkowe-zgloszenia/issues/248 (ale to jedno akurat zduplikował xMaap)
i być może jeszcze więcej duplikatów jest na polskim repo, nie wiem czy blocker999 wykrada moje zgłoszenia czy to tylko przypadek, kiedyś pisałeś, że ponoć miał w planach wykradać reguły z I don't care about cookies i Fanboy's Cookie List do polskiej listy ciasteczkowej, czy coś takiego.

**Comment by krystian3w** [comment]
On tu nie zagląda, a sam nawet woli nie ruszać sociala i zgłasza do majka.

**Comment by gaargul** [comment]
Na pewno zajrzał tu https://github.com/MajkiIT/polish-ads-filter/issues/12256#issuecomment-467444306, więc był na tym repo...
